FROM python:3.13-slim

WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r ./requirements.txt
COPY . .

# ARG AWS_ACCESS_KEY_ID
# ARG AWS_SECRET_ACCESS_KEY
# ARG AWS_SESSION_TOKEN
# ARG AWS_REGION
# ARG EFS_PATH
# ARG S3_BUCKET_NAME
# ARG API_GATEWAY_URL

# ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
# ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
# ENV AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
# ENV AWS_REGION=${AWS_REGION}
# ENV EFS_PATH=${EFS_PATH}
# ENV S3_BUCKET_NAME=${S3_BUCKET_NAME}
# ENV API_GATEWAY_URL=${API_GATEWAY_URL}


EXPOSE 5000

CMD ["python", "./app.py"]